### ISSUE TITLE
I want to be able to define subprojects and be able to navigate between them and the parents

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#124]

**Comment by rebeccamccabe** [comment]
I am trying to link my pipelines in a submodule and parent repository for my thesis. The repository structure is the same as described [here](https://github.com/orgs/calkit/discussions/359), with the dissertation in the MDOcean repo. I have the latex import and compile working, and the pipeline stages for the various outputs in the MDOcean repo, but I can't get the OpenFLASH pipeline to run as a dependency of my MDOcean pipeline. Any suggested workarounds in the meantime before this feature is implemented?

**Comment by petebachant** [comment]
I should have some time to work on this over the weekend. Is there any way you can share the parent repo so I can use that as a test case? I would keep it private of course.

**Comment by rebeccamccabe** [comment]
Yes, I appreciate it! The parent repo is actually just MDOcean so it is
already public, in the pubs/dissertation folder. I merged an initial
version to main yesterday (the pipeline there is stale though because I had
to meet a deadline before the longest running stages had completed), and I
am making updates in the overleaf and thesis-update branches, which should
have a less-stale version.

-Becca

**Comment by petebachant** [comment]
Released in v0.39.0. Let me know if it doesn't work like you hoped!

**Comment by rebeccamccabe** [comment]
When compiling, I get the following error for the subproject stage:
```
Compiling DVC pipeline
ERROR: Same item(s) are defined as both a dependency and an output in stage: OpenFLASH.
```
[Link to logs](https://github.com/symbiotic-engineering/MDOcean/actions/runs/25634393346/job/75243604689).

**Comment by petebachant** [comment]
Should be fixed in v0.39.1

**Comment by rebeccamccabe** [comment]
Now I get an error about the subproject not having a run cache. Here is the verbose output:
```
$ calkit run -v make-calkit-stages
Getting system information
Checking system-level dependencies
Checking environments
Checking environments for subproject: mdocean/simulation/modules/OpenFLASH
mdocean/simulation/modules/OpenFLASH/openflash-on-main: {'success': True, 'cached': True}
mdocean/simulation/modules/OpenFLASH/tex: {'success': True, 'cached': True}
mdocean/simulation/modules/OpenFLASH/openflash-on-branch: {'success': True, 'cached': True}
Compiling DVC pipeline
Starting run ID: faf67d07c9644c4eb035c61749d1f30e
Saving logs to .calkit/logs/2026-05-10T23-54-21-faf67d07c9644c4eb035c61749d1f30e.log
2026-05-10 19:54:21,422 DEBUG: v3.67.1 (pip), CPython 3.12.11 on Linux-5.15.0-139-generic-x86_64-with-glibc2.31
2026-05-10 19:54:21,422 DEBUG: command: repro make-calkit-stages --verbose
2026-05-10 19:54:21,466 DEBUG: Assuming 'make-calkit-stages' to be a stage inside 'dvc.yaml'    
2026-05-10 19:54:25,886 DEBUG: Lockfile 'dvc.lock' needs to be updated.
Stage 'make-drag-integral' didn't change, skipping                                                                                                                                
Stage 'make-var-bounds' didn't change, skipping                                                                                                                                   
2026-05-10 19:54:26,961 DEBUG: stage: 'OpenFLASH' changed.
2026-05-10 19:54:26,969 DEBUG: stage: 'OpenFLASH' changed.
2026-05-10 19:54:26,999 DEBUG: built tree 'object d751713988987e9331980363e24189ce.dir'                                                                                           
2026-05-10 19:54:27,000 DEBUG: built tree 'object d751713988987e9331980363e24189ce.dir'                                                                                           
2026-05-10 19:54:27,001 DEBUG: built tree 'object d751713988987e9331980363e24189ce.dir'                                                                                           
2026-05-10 19:54:27,003 ERROR: failed to reproduce 'OpenFLASH': dependency 'mdocean/simulation/modules/OpenFLASH/.calkit/notebooks/cleaned/analysis/low_m0_plots.ipynb' does not exist
Traceback (most recent call last):
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/run.py", line 174, in run_stage
    stage.repo.stage_cache.restore(stage, dry=dry, **kwargs)
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/cache.py", line 196, in restore
    raise RunCacheNotFoundError(stage)
dvc.stage.cache.RunCacheNotFoundError: No run-cache for OpenFLASH

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/repo/reproduce.py", line 187, in _reproduce
    ret = repro_fn(stage, upstream=upstream, force=force_stage, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/repo/reproduce.py", line 117, in _reproduce_stage
    ret = stage.reproduce(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/decorators.py", line 44, in rwlocked
    return call()
           ^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/__init__.py", line 448, in reproduce
    self.run(**kwargs)
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/decorators.py", line 44, in rwlocked
    return call()
           ^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/__init__.py", line 601, in run
    self._run_stage(dry, force, **kwargs)
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/decorators.py", line 44, in rwlocked
    return call()
           ^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/__init__.py", line 628, in _run_stage
    return run_stage(self, dry, force, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/run.py", line 179, in run_stage
    stage.save_deps()
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/stage/__init__.py", line 507, in save_deps
    dep.save()
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/dependency/base.py", line 51, in save
    super().save()
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/output.py", line 692, in save
    raise self.DoesNotExistError(self)
dvc.dependency.base.DependencyDoesNotExistError: dependency 'mdocean/simulation/modules/OpenFLASH/.calkit/notebooks/cleaned/analysis/low_m0_plots.ipynb' does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/cli/__init__.py", line 212, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/cli/command.py", line 30, in do_run
    return self.run()
           ^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/commands/repro.py", line 11, in run
    stages = self.repo.reproduce(**self._common_kwargs, **self._repro_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/repo/__init__.py", line 59, in wrapper
    return f(repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/repo/scm_context.py", line 150, in run
    return method(repo, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/repo/reproduce.py", line 248, in reproduce
    return _reproduce(steps, graph=graph, on_error=on_error or "fail", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/repo/reproduce.py", line 191, in _reproduce
    _raise_error(exc, stage)
  File "/home/becca/.local/share/uv/tools/calkit-python/lib/python3.12/site-packages/dvc/repo/reproduce.py", line 155, in _raise_error
    raise ReproductionError(f"failed to reproduce{segment} {names}") from exc
dvc.exceptions.ReproductionError: failed to reproduce 'OpenFLASH'

2026-05-10 19:54:27,006 DEBUG: Analytics is enabled.
2026-05-10 19:54:27,046 DEBUG: Trying to spawn ['daemon', 'analytics', '/tmp/tmpazu2to2i', '-v']
2026-05-10 19:54:27,053 DEBUG: Spawned ['daemon', 'analytics', '/tmp/tmpazu2to2i', '-v'] with pid 2965421
Error: Pipeline failed
```

**Comment by petebachant** [comment]
v0.39.2 can now compile and run your full pipeline with subprojects on my machine, but it fails at one stage:

```
Running stage 'postpro-FitOlaya':                                                              
> matlab -noFigureWindows -batch "add_mdocean_path(); obj=FitOlaya; obj.run_all_from_load();"
Error using fit>iFit (line 407)
Inf computed by model function, fitting cannot continue.
Try using or tightening upper and lower bounds on coefficients.

Error in fit (line 117)
[fitobj, goodness, output, convmsg] = iFit( xdatain, ydatain, fittypeobj, ...
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in FitOlaya.post_process_fcn>perform_auto_fit (line 933)
    f = fit(log(x(not_nan)), log(y(not_nan)), ft, fo);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in FitOlaya.post_process_fcn>plot_fit_sep_alpha_beta (line 512)
                f = perform_auto_fit(x,y,ft,fo);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in FitOlaya.post_process_fcn>plot_fit_and_coeffs_sep_alpha_beta (line 428)
    [fits, fig_auto]   = plot_fit_sep_alpha_beta(x_cell, y_cell, alpha_vec, beta_vec, ft, fo, x_string, y_string, true);
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in FitOlaya.post_process_fcn>fit_and_plot_case4 (line 344)
    figs_sep = plot_fit_and_coeffs_sep_alpha_beta(case_4.kh_Rx_over_Rp_alpha2_over_beta, case_4.f_over_H0_exp_sqrt_kh, ...
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in FitOlaya.post_process_fcn (line 37)
    figs_case4 = fit_and_plot_case4(case_4, case_2, idxs_alpha_cell, idxs_beta_cell, ft, fo, spar_exc);
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in GenericAnalysis/run_post_process (line 127)
                obj.tab_colspecs] = obj.post_process_fcn(obj.intermed_result_struct);
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in GenericAnalysis/run_all_from_load (line 222)
            obj = obj.run_post_process();
                  ^^^^^^^^^^^^^^^^^^^^^^
 
ERROR: failed to reproduce 'postpro-FitOlaya': failed to run: matlab -noFigureWindows -batch "add_mdocean_path(); obj=FitOlaya; obj.run_all_from_load();", exited with 1
Error: Pipeline failed
```

FYI: I also had to install the mapping and curve fitting toolboxes, which aren't in the README, so I created #890 to allow projects to declare this kind of check so it's not a surprise.

**Comment by rebeccamccabe** [comment]
Ok, thanks! That stage has worked fine for me, I will look into it and whether it's a matlab version behavior difference or something else.
